# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 23:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0002_auto_20170522_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zip_code', models.IntegerField(default=0)),
                ('city', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('search_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_terms', models.CharField(default=None, max_length=30, null=True)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Location')),
            ],
        ),
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[(b'undecided', b'Undecided'), (b'hate', b'Hated'), (b'like', b'Liked'), (b'love', b'Loved')], default=b'undecided', max_length=10)),
                ('last_visted', models.DateField(default=b'null')),
            ],
        ),
        migrations.RemoveField(
            model_name='search',
            name='user',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='hated',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='id',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='last_dining',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='loved',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='search',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='times_gone',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='trying',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.AddField(
            model_name='visithistory',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='visithistory',
            name='search_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.SearchHistory'),
        ),
        migrations.AddField(
            model_name='visithistory',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
