# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-28 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20180721_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visithistory',
            name='rating',
            field=models.CharField(choices=[('HATE', 'Hated'), ('LIKE', 'Liked'), ('LOVE', 'Loved'), ('UNDECIDED', 'Undecided'), ('SAVE', 'Saved')], default='undecided', max_length=10),
        ),
    ]
