# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-28 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20180728_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visithistory',
            old_name='last_visted',
            new_name='last_visited',
        ),
    ]
