# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-03 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20170604_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visithistory',
            name='last_visted',
            field=models.DateField(default='null'),
        ),
        migrations.AlterField(
            model_name='visithistory',
            name='rating',
            field=models.CharField(choices=[('undecided', 'Undecided'), ('hate', 'Hated'), ('like', 'Liked'), ('love', 'Loved')], default='undecided', max_length=10),
        ),
    ]
