# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-29 17:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0004_auto_20180303_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_type',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Location'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visithistory',
            name='rating',
            field=models.CharField(choices=[('selected', 'Selected'), ('undecided', 'Undecided'), ('hate', 'Hated'), ('like', 'Liked'), ('love', 'Loved')], default='undecided', max_length=10),
        ),
    ]
